Models/MeetingInfo.cs
namespace MeetingApp.Models
{
    public class MeetingInfo
    {
        public int Id { get; set; }
        public string? Location { get; set; }
        public DateTime Date { get; set; }
        public int NumberOfPeople { get; set; }
    }
}

Models/Repository.cs
namespace MeetingApp.Models
{
    public static class Repository
    {
        static Repository()
        {
            _users.Add(new UserInfo() {Id=1, Name = "Ali", Email = "abc@gmail.com", Phone = "11111", WillAttend = true });
            _users.Add(new UserInfo() { Id = 2, Name = "Ahmet", Email = "abcd@gmail.com", Phone = "22222", WillAttend = false });
            _users.Add(new UserInfo() { Id = 3, Name = "Canan", Email = "abce@gmail.com", Phone = "33333", WillAttend = true });
        }

        private static List<UserInfo> _users = new();

        public static List<UserInfo> Users { get { return _users; } }

        public static void CreateUser(UserInfo user)
        {
            user.Id = _users.Count + 1;
            _users.Add(user);
        }

        public static UserInfo? GetById(int id) => _users.FirstOrDefault(u => u.Id == id);
    }
}

Models/UserInfo.cs
using System.ComponentModel.DataAnnotations;

namespace MeetingApp.Models
{
    public class UserInfo
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Ad alanı zorunlu")]
        public string? Name { get; set; }
        [Required(ErrorMessage ="Telefon alanı zorunlu")]
        public string? Phone { get; set; }
        [Required(ErrorMessage ="Email alanı zorunlu")]
        [EmailAddress(ErrorMessage ="Hatalı email")]
        public string? Email { get; set; }
        [Required(ErrorMessage ="Katılım durumunuzu belirtiniz")]
        public bool? WillAttend { get; set; }
    }
}

Controllers/HomeController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            int saat = DateTime.Now.Hour;

            ViewData["Selamlama"] = saat > 12 ? "İyi günler" : "Günaydın";
            //ViewData["Username"] = "Çınar";

            MeetingInfo meetinginfo = new()
            {
                Id = 1,
                Location = "İstanbul, Abc Kongre Merkezi",
                Date = new DateTime(year: 2024, month: 01, day: 20, hour: 20, minute: 00, second: 00),
                NumberOfPeople = Repository.Users.Where(u => u.WillAttend == true).Count()
            };

            return View(model:meetinginfo);
        }
    }
}

Controllers/MeetingController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class MeetingController : Controller
    {
        [HttpGet]
        public IActionResult Apply()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Apply(UserInfo model)
        {
            if (ModelState.IsValid)
            {
                Repository.CreateUser(model);
                ViewBag.UserCount = Repository.Users.Where(info => info.WillAttend == true).Count();
                return View("Thanks", model);
            }
            else
            {
                return View(model);
            }

        }

        [HttpGet]
        public IActionResult List()
        {
            return View(Repository.Users);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            return View(Repository.GetById(id));
        }
    }
}

Views/Home/Index.cshtml
@model MeetingInfo
@{
    Layout = "_Layout2";
    ViewBag.Title = "Toplantı Başvuru";
}
@* Home/Index *@

<main class="text-center">

<h1 class="h4">@ViewData["Selamlama"]</h1>
<p>Toplantı katılım durumunuzu bildiriniz.</p>

<div class="card my-2">
    <ul class="list-group list-group-flash">
        <li class="list-group-item">@Model.Location</li>
        <li class="list-group-item">@Model.Date tarihinde gerçekleşecek</li>
        <li class="list-group-item">@Model.NumberOfPeople Katılımcı</li>
    </ul>
</div>

<a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Başvuru Yap</a>

</main>

Views/Meeting/Apply.cshtml
@model UserInfo

@{
    ViewBag.Title = "Başvuru Formu";
}


@*Meeting/Apply*@
<h1 class="h4 text-center">Toplantı Katılım Formu</h1>
<form method="post" action="/Meeting/Apply" novalidate>
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Ad Soyad</label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Telefon</label>
        <input asp-for="Phone" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Eposta</label>
        <input asp-for="Email" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="WillAttend" class="form-label">Katılım Durumu</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="@null">Seçiniz</option>
            <option value="true">Evet, Geliyorum</option>
            <option value="false">Hayır, Gelmiyorum</option>
        </select>
    </div>

    <button class="btn btn-primary" type="submit">Kaydet</button>
</form>

Views/Meeting/Details.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Detayı";
}

@{
    string className = Model.WillAttend == true ? "primary" : "danger";
}

<main class="text-center">
    <h1 class="h4">Başvuru Detayı</h1>

    <p>
        <span class="badge text-bg-@className">
            @if(Model.WillAttend==true)
            {
                <text>Katılıyor</text>
            }
            else
            {
                <text>Katılmıyor</text>
            }
        </span>
    </p>

    <p>İsim: @Model.Name</p>
    <p>Email: @Model.Email</p>
    <p>Telefon: @Model.Phone</p>
    <a asp-controller="Meeting" asp-action="List" class="btn btn-outline-@className">Katılımcı Listesi</a>
</main>

Views/Meeting/List.cshtml
@model List<UserInfo>
@{
    ViewBag.Title = "Toplantı Katılım Listesi";
}

@*Meeting/List*@
<main class="text-center">
    <h1 class="h4">Toplantı Katılım Listesi</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Ad</td>
                <td>Katılım Durumu</td>
                <td></td>
            </tr>
        </thead>
        <tbody>


            @{
                int i = 0;
            }

            @foreach (var user in Model)
            {
                string durum = user.WillAttend == true ? "Evet" : "Hayır";
                string className = user.WillAttend == true ? "table-success" : "table-danger";

                if (user.WillAttend == true) { i++; }

                <tr class="@className">
                    <td>@user.Name</td>
                    <td>@durum</td>
                    <td><a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detay</a></td>
                </tr>
            }

        </tbody>
    </table>

    <div class="card">
        <div class="card-body">
            <span>Katılımcı sayısı: @i</span>
        </div>
    </div>


</main>

Views/Meeting/Thanks.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Durumu";
}

@*Meeting/Index*@
<main class="text-center">

    <h1 class="h4">Başvuru Durumu</h1>

    @if (Model.WillAttend == true)
    {
        <p>Teşekkürler, @Model.Name toplantıya sizinle birlikte @ViewBag.UserCount kişi katılıyor.</p>
        <a class="btn btn-sm btn-outline-primary" href="/meeting/list">Katılımcıları Listele</a>
    }
    else
    {
        <p>@Model.Name, katılmadığından dolayı üzgünüz.</p>
        <a class="btn btn-sm btn-outline-primary" href="/Meeting/Apply">Başvuru Formu</a>
    }


</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <link rel="stylesheet" href="/lib/twitter-bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/styles.css" /> @*Validation'lari biçimlendirmek için yazıldı*@
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
    <div class="bg-primary text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <link rel="stylesheet" href="/lib/twitter-bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/styles.css" /> @*Validation'lari biçimlendirmek için yazıldı*@
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
    <div class="bg-danger text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>